### ISSUE TITLE
Weather not working

### ISSUE THREAD

**Issue by MACscr** [HomeAutomationForGeeks/openhab-controlpanel#1]
I have a valid api key, ive tried your test Station ID and my own station ID, but i still only get back the following responses:

`````` jQuery1111003587314716463652_1434722388388(
{
  "response": {
  "version":"0.1",
  "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
  "features": {
  "conditions": 1
  }
        ,
    "error": {
        "type": "querynotfound"
        ,"description": "No cities match your search query"
    }
    }
}
);```

from either of the json api files
``````

**Comment by tdesplenter** [comment]
Depending on what you're querying on Weather Underground you need a different prefix. For example if you're querying a weather station, the prefix is "pws". 

Try this URL where you only replace "APIKEY":

http://api.wunderground.com/api/APIKEY/conditions/q/pws:KNYNEWYO118.json

**Comment by HomeAutomationForGeeks** [comment]
Depending on what you're querying on Weather Underground you need a different prefix. For example if you're querying a weather station, the prefix is "pws".

Try this URL where you only replace "APIKEY":

http://api.wunderground.com/api/APIKEY/conditions/q/pws:KNYNEWYO118.json

**Comment by MACscr** [comment]
The weather station id didn't work, i ended up having to use: http://api.wunderground.com/api/XXXXXXXXX/conditions/q/zmw:61601.1.99999.json

**Comment by HomeAutomationForGeeks** [comment]
Odd. Maybe some stations aren't directly available via public API? I added some explanation to the readme about the pws prefix. 

I'll close this issue now as it seems to be a Weather Underground peculiarity rather than an issue with the dashboard.
